app:
  host: "127.0.0.1"
  port: 6122
  # 可选值：debug release test, 和 Gin 的 mode 对齐
  mode: "debug"
  admin_username: "admin"
  admin_password: "123456"

mysql:
  host: "127.0.0.1"
  username: "root"
  password: "123456"
  port: 3306
  db_name: "fuxiaochen"

jwt:
  secret: "jwt_secret"
  # token 过期时间 单位: 小时
  expire_duration: 1

log:
  filepath: "./log/app.log"
  max_size: 1
  max_backups: 5
  max_age: 30
  compress: false